import json
import ollama

def avaliar_redacao(json_input: str) -> str:
    """
    Receives a JSON string with 'tema', 'texto', and 'competencias',
    and returns the textual evaluation generated by the Gemma model via Ollama.
    """
    # Parse JSON
    data = json.loads(json_input)
    redacao = data 

    # Acessa o primeiro elemento (dicionário) da lista # por enquanto (acima), acessa direto às chaves como se o JSON fossem um único dicionário, só que é uma lista de dicionários (modificar depois)
    #redacao = data[0] 

    # Obtém dados do dicionário da redação
    tema = redacao["tema"]
    texto = redacao["texto"]
    competencias_dados = redacao["competencias"] 

    # Monta o system prompt com as competências
    competencias_str = "\n".join([
        f"- **{comp['competencia']}**: Nota {comp['nota']} | Motivo: {comp['motivo']}"
        for comp in competencias_dados
    ])

    # Monta o system prompt
    system_prompt = (
        "Você é um avaliador pedagógico especialista em produção textual no contexto do ENEM. "
        "Sua tarefa é analisar uma redação escrita por um estudante, considerando as notas atribuídas "
        "a cada uma das cinco competências avaliativas do exame e também o tema (i.e., a proposta) da redação correspondente.\n\n"
        "Você deve gerar sugestões específicas de melhoria para o texto, sempre levando em conta:\n"
        "- O conteúdo integral da redação produzida.\n"
        "- As notas atribuídas em cada uma das cinco competências (0–200).\n"
        "- O tema da redação (proposta e/ou texto motivador).\n\n"
        f"**Competências Avaliadas:**\n{competencias_str}\n\n"
        "Apresente sua resposta no seguinte formato:\n\n"
        "---\n"
        "**Competência X** – Nota: [nota atribuída]\n"
        "[Até 3 sugestões focadas nessa competência, levando em conta o conteúdo da redação, o escopo do tema e a nota recebida]\n"
        "---\n\n"
        "Importante: Use o tema da redação para avaliar a pertinência temática e o foco argumentativo do estudante. "
        "Se a proposta de intervenção for vaga, sugira maneiras de conectá-la melhor ao problema central. "
        "Não reescreva a redação nem emita julgamentos genéricos; concentre-se em orientar melhorias concretas."
    )

    # Monta o user prompt
    competencias_str_user = "\n".join([
        f"Competência {i+1}: Nota {comp['nota']} | {comp['competencia']}"
        for i, comp in enumerate(competencias_)
    ])

    user_prompt = (
        f"Tema da redação:\n{tema}\n\n"
        f"Texto da redação:\n{texto}\n\n"
        f"Notas por competência:\n{competencias_str_user}"
    )

    # Chamada ao modelo via Ollama
    response = ollama.chat(
        model="gemma:7b",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )

    return response["message"]["content"]
    

# Exemplo de uso
if __name__ == "__main__":
    json_input_example = json.dumps([{
        "tema": "Privatização do saneamento básico",
        "texto": "Hegel discorre sobre a importância de um pensamento bilateral para a formação da consciência dos indivíduos, que consiste em estar no mundo e ver o mundo por completo. Destarte, tal direito constitucional converte a ser pouco igualitário e torna-se um reflexo da sociedade contemporânea, na qual as relações de lucro e interesse predominam.Portanto, cabe ao Poder Executivo promover uma reestruturação nos complexos sanitários mediante a correta distribuição de capital público. Assim, o poder não deixar de emanar sobre o povo e o pensamento de Hegel tornar-se-à uma realidade para essa geração e futuras.",
        "texto_comentado": "()Hegel discorre sobre a importância de um pensamento bilateral para a formação da consciência dos indivíduos, que consiste em estar no mundo e ver o mundo por completo. Destarte, tal direito constitucional converte a ser pouco igualitário e torna-se um reflexo da sociedade contemporânea, na qual as relações de lucro e interesse predominam.(Explore mais os argumentos)(Boa estratégia coesiva)Portanto, cabe ao Poder Executivo (Boa. Apresenta o agente e faz o detalhamento)promover uma reestruturação nos complexos sanitários mediante a correta distribuição de capital público. Assim, o poder não deixar de emanar sobre o povo e o pensamento de Hegel tornar-se-à uma realidade para essa geração e futuras.(A proposta está incompleta)",
        "comentarios": "Ótima produção textual. Mantenha os aspectos positivos. Não deixe de exercitar a sua escrita.",
        "nota": "850.0",
        "titulo": "\"...\"",
        "id": "16178",
        "link": "https://vestibular.brasilescola.uol.com.br/banco-de-redacoes/16178",
        "competencias": [
            {"competencia": "Domínio da modalidade escrita formal", "nota": "150", "motivo": "Nível 4 - Demonstra bom domínio da modalidade escrita formal da língua portuguesa e de escolha de registro, com poucos desvios gramaticais e de convenções da escrita."},
            {"competencia": "Compreender a proposta e aplicar conceitos das várias áreas de conhecimento para desenvolver o texto dissertativo-argumentativo em prosa", "nota": "200", "motivo": "Nível 5 - Desenvolve o tema por meio de argumentação consistente, a partir de um repertório sociocultural produtivo e apresenta excelente domínio do texto dissertativo-argumentativo."},
            {"competencia": "Selecionar, relacionar, organizar e interpretar informações em defesa de um ponto de vista", "nota": "150", "motivo": "Nível 4 - Apresenta informações, fatos e opiniões relacionados ao tema, de forma organizada, com indícios de autoria, em defesa de um ponto de vista."},
            {"competencia": "Conhecimento dos mecanismos linguísticos necessários para a construção da argumentação", "nota": "200", "motivo": "Nível 5 - Articula bem as partes do texto e apresenta repertório diversificado de recursos coesivos."},
            {"competencia": "Proposta de intervenção com respeito aos direitos humanos", "nota": "150", "motivo": "Nível 4 - Elabora bem proposta de intervenção relacionada ao tema e articulada à discussão desenvolvida no texto."}
        ],
        "contexto_tema": "A possível privatização do saneamento básico tem levantado uma série de discussões que se mostram contra e a favor. Apesar de ter como ideia fundamental levar água tratada aos que não possuem acesso, tendo em vista a falta de investimento público, por exemplo, muitos se mostram contra argumentando que essa estratégia vai dificultar ainda mais o acesso a esse serviço. Tendo isso em vista, a proposta do Banco de Redações do mês de agosto é que você desenvolva uma redação sobre o seguinte tema: Privatização do saneamento básico"
    }])

    resultado = avaliar_redacao(json_input_example)
    print(resultado)
